---
# This playbook restart the stack of the application to its initial state
# 1. bringing down the stack:
#   1. bring down the loadbalancer, since database or server might be serving requests
#   2. bring down the server
#   3. bring down database
# 2. bringing the stack up again
#   1. bring up database
#   2. bring up webserver
#   3. bring up loadbalancer
#
# [ BRINGIND DOWN STACK SEQUENCE ]
- hosts: loadbalancer
  tasks:
    - service: name=nginx state=stopped

- hosts: webserver
  tasks:
    - service: name=apache2 state=stopped

# NOTE: we are going to set the `state=restarted` because in the next task we will start it again
# so we mash these two states together and set the `state=restarted` instead
- hosts: database
  tasks:
    - service: name=mysql state=restarted

# [ BRINGING UP STACK SEQUENCE ]
- hosts: webserver
  tasks:
    - service: name=apache2 state=started

- hosts: loadbalancer
  tasks:
    - service: name=nginx state=started
