version: "3"
services:
 # base service
  base:
    build: ./base/
    image: ansible_base
 
 # controller service
  controller:
    links:
      - base
    build: ./controller/
    image: ansible_master
    hostname: controller
    container_name: controller
    command: ["/usr/sbin/sshd","-D"]
    volumes:
      - type: volume
        source: ansible_vol
        target: /var/ans
      - type: bind
        source: ../ansible-files/codes # bind the ansible-files folder to / code
        target: /codes/

  # load balancer machine
  loadbalancer:
    links:
      - base
      - controller
    build: ./host/
    image: ansible_host
    hostname: loadbalancer
    container_name: lb01
    command: ["/var/run.sh"]
    volumes:
     - ansible_vol:/var/ans

  # first webserver machine
  webserver-1:
    links:
      - base
      - controller 
      - loadbalancer 
    image: ansible_host
    hostname: web01
    container_name: web01
    command: ["/var/run.sh"]
    volumes:
     - ansible_vol:/var/ans

  # second web-server machine
  webserver-2:
    links:
      - base
      - controller 
      - loadbalancer 
    image: ansible_host
    hostname: web02
    container_name: web02
    command: ["/var/run.sh"]
    volumes:
     - ansible_vol:/var/ans

  # Databse machine
  database:
    links:
      - base
      - controller
      - loadbalancer
    image: ansible_host
    hostname: database
    container_name: db01
    command: ["/var/run.sh"]
    volumes:
     - ansible_vol:/var/ans

volumes:
  ansible_vol:
